##### TEST #####

version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: echo "First without dependence"
      - run: sudo gem install fastlane -NV
      - run: fastlane custom_lane
  clean-and-build:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: echo "Install Fastlane"
      #- run:
      #    name: Fetch CocoaPods Specs
      #    command: |
      #      curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install Fastlane
          command: sudo gem install fastlane -NV
      #- run : xcodebuild -allowProvisioningUpdates -scheme PlayingCard -project ./PlayingCard.xcodeproj 
                        #-showBuildSettings
      #- run: sudo fastlane init
      #- run: sudo fastlane xcclean
      #- run: sudo fastlane gym #xcodebuild
      - run: xcodebuild clean -allowProvisioningUpdates -scheme PlayingCard -project ./PlayingCard.xcodeproj
      #

workflows:
  version: 2
  test_release:
    jobs:
      - one
    #  - clean-and-build
      
