# version: 2
# jobs:
#   one:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "A first hello"
#       - run: sleep 25
#   two:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "A more familiar hi"
#       - run: sleep 15
# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two


# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WebTests

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
