##### TEST #####

version: 2
jobs:
  one:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: echo "First without dependence"
      - run: sleep 25
  install-fastlane:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: echo "Install Fastlane"
      - run: sleep 25
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install Fastlane
          command: sudo gem install fastlane -NV
      - run: fastlane scan

workflows:
  version: 2
  test_release:
    jobs:
    #  - one
      - install-fastlane
      
