##### TEST #####

version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      #- checkout
      - run: fastlane scan
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      #- checkout
      - deploy:
          #name: Deploy
          command: fastlane gym

workflows:
  version: 2
  test_release:
    jobs:
      - test
      - deploy:
          requires:
            test
          filters:
            branches:
              only: release
