# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
  	slack(
        pretext: "A new build  was successfully uploaded to Test Flight 🚀",
        default_payloads: [:git_branch, :last_git_commit, :git_author],
        slack_url: ENV["SLACK_URL_IOS_CHANNEL"]
    )
  end
end

error do |lane, exception|
    slack(
        pretext: "There was an error running custom_lane",
        default_payloads: [:git_branch, :last_git_commit, :git_author],
        success: false,
        slack_url: ENV["SLACK_URL_MICHEL"]
    )
end
